### ISSUE TITLE
Easily crash when using mouse-3

### ISSUE THREAD

**Issue by neutrous** [railwaycat/emacs-mac-port#80]
When upgrade to the version 5.2, i found it's easily to make emacs crashing when using mouse-3 to click any links in buffer! Although it's rare to use mousing in my daily using of emacs......

I tried the [Universal](http://emacsformacosx.com/) to reproduce this problem, however, it seems the issue is specific to **Mac Port**.

**Comment by neutrous** [comment]
Emm.....
When using `emacs -Q`, everything looks ok.
I think it's relevant to my personal configuration mistakes.

**Comment by pitkali** [comment]
Well, personally I don't think crashing is acceptable, even if configuration is broken. What it really tells us that there's something in your configuration that triggers the crash, and if we, or the actual author of the port are supposed to fix it, it would help tremendously to get some small configuration that would enable us to reproduce the problem.
