### ISSUE TITLE
README-mac and NEWS-mac files does not exist

### ISSUE THREAD

**Issue by zzp0** [railwaycat/emacs-mac-port#81]
Installed `emacs-mac` by `brew`, that two files do not exist in `/usr/local/Cellar/emacs-mac/emacs-24.4-mac-5.3` directory.

**Comment by railwaycat** [comment]
You are right. Homebrew formula does not install these two files to target directory. 

I will close this one and open an issue in homebrew-emacsmacport repo.

**Comment by railwaycat** [comment]
railwaycat/homebrew-emacsmacport#9
