### ISSUE TITLE
Emacs always moves to background when changing desktops

### ISSUE THREAD

**Issue by mankoff** [railwaycat/emacs-mac-port#82]
If I have Emacs.app and application X open on a desktop, and Emacs.app is the foreground app, when I switch to a different desktop, and then switch back to the desktop with Emacs.app, application X always moves to the foreground.

All other applications remember which is foreground in any given Desktop. That means even if I have App A and B in Desktop 1 and 2, I can set A to FG in 1, B to FG in 2, and switch desktops and it remains as I set it. Emacs.app should obey this behavior too.

**Comment by sgr** [comment]
In my case, the behavior had subsided by modifying init.el as follows:

```emacs-lisp
;; (menu-bar-mode -1)
```

**Comment by richardsc** [comment]
I can't reproduce this behavior. Do you see this with vanilla startup options?

**Comment by mankoff** [comment]
Hi @richardsc :). Thanks @sgr, commenting that line fixed it.
