### ISSUE TITLE
Symbol's function definition error

### ISSUE THREAD

**Issue by MagisDing** [railwaycat/emacs-mac-port#91]
I upgraded the emac-mac to 24.5 through homebrew today, and it always pops out "symbol's function definition is void: esk-prog-mode-hook" in the mini buffer. I tried to clear my init.el file and reinstall the emacs, the error still exists. How do I get rid of this?

Thanks

**Comment by railwaycat** [comment]
`esk-prog-mode-hook` looks like something from Emacs starter kit, right?

**Comment by MagisDing** [comment]
But I didn't install the starter-kit， made the configuration by myself.

**Comment by railwaycat** [comment]
@MagisDing But this is definitely not from Emacs, mac port or official. 

How about have a try: `/Applications/Emacs.app/Contents/MacOS/Emacs -q`

**Comment by MagisDing** [comment]
@railwaycat What is the meaning of "-q"? That makes Emacs to the origin one, no error pops, which is what I want, thanks! But I am used to launching emacs directly by clicking the icon.

**Comment by railwaycat** [comment]
`-q` means not load any init file. 

If your emacs works OK while with `-q` but not working while without, then there must some config files in somewhere you not notice (and you might not want them).

**Comment by MagisDing** [comment]
Does "leaving .init.el blank" equal "not loading any init file"? Because I have already done like the former one but still got the error. Anyway I am trying to make a homebrew reinstallation and customise the init file line by line, see what I will get. Thanks.

**Comment by railwaycat** [comment]
http://www.gnu.org/software/emacs/manual/html_node/emacs/Init-File.html

Check your `~/.emacs`, `~/.emacs.el`, or `~/.emacs.d/init.el`, rename them if necessary.

**Comment by MagisDing** [comment]
I reinstalled emacs through Homebrew, got the same error. I checked all the possible config files, they were all blank. So wierd....

**Comment by pitkali** [comment]
Well then, what does `grep -R esk-prog-mode-hook ~/.emacs*` say?

**Comment by MagisDing** [comment]
Anyway I have made an "absolute clean reinstallation" by deleting the folder ~/.emac.d, thanks for your help. @pitkali @railwaycat .
