### ISSUE TITLE
option to zoom frame instead of buffer

### ISSUE THREAD

**Issue by sellout** [railwaycat/emacs-mac-port#95]
I usually want to zoom a frame instead of a buffer, so mapping pinch to frame-level zooming rather than buffer zooming would be great.

The [zoom-frm](http://www.emacswiki.org/emacs/zoom-frm.el) library already offers this, so maybe having `mac-magnify-text-scale` use `zoom-in/out` rather than `text-scale-adjust` directly would be reasonable?

If you think so, I can submit a PR.

**Comment by railwaycat** [comment]
Hi @sellout, there might some misunderstanding. If you would like to give suggestion/contribution to emacs mac ports developing, you will need to speak to the developer YAMAMOTO Mitsuharu <mituharu@math.s.chiba-u.ac.jp>

**Comment by railwaycat** [comment]
BTW, thank you for your solarized theme for emacs:)
